[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"

[etherscan]
amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
